services:
  web:
    container_name: topgunclub-web
    env_file:
      - .env.local
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"

      # Servicio
      - "traefik.http.services.topgunclub-service.loadbalancer.server.port=3000"

      # Router HTTPS (principal)
      - "traefik.http.routers.topgunclub.rule=Host(`topgunclub.com.bo`) || Host(`www.topgunclub.com.bo`)"
      - "traefik.http.routers.topgunclub.entrypoints=websecure"
      - "traefik.http.routers.topgunclub.tls=true"
      - "traefik.http.routers.topgunclub.tls.certresolver=letsencrypt"
      - "traefik.http.routers.topgunclub.service=topgunclub-service"

      # Router HTTP (redirección automática a HTTPS)
      - "traefik.http.routers.topgunclub-http.rule=Host(`topgunclub.com.bo`) || Host(`www.topgunclub.com.bo`)"
      - "traefik.http.routers.topgunclub-http.entrypoints=web"
      - "traefik.http.routers.topgunclub-http.middlewares=redirect-to-https"
      - "traefik.http.routers.topgunclub-http.service=topgunclub-service"

      # Middleware global de redirección
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

networks:
  web:
    external: true
